<?php
/* Smilies for bbPress Post Toolbar.
 * These smilies made by Laurent Schwarzenberger.
 */

$wpsmiliestrans = array(
	':)'  => 'smile.png',
	'(:'  => 'smile.png',
	':-)'  => 'smile.png',
	'(-:'  => 'smile.png',
	':('  => 'sad.png',
	'):'  => 'sad.png',
	':-('  => 'sad.png',
	')-:'  => 'sad.png',
	';)'  => 'wink.png',
	';-)'  => 'wink.png',
	':|'  => 'lameface.png',
	':-|'  => 'lameface.png',
	':D'  => 'laugh2.png',
	':-D'  => 'laugh2.png',
	':S'  => 'confused.png',
	':-S'  => 'confused.png',
	':P'  => 'tongue.png',
	':-P'  => 'tongue.png',
	':O'  => 'gasp.png',
	':-O'  => 'gasp.png',
	':cry:'  => 'cry.png',
	';('  => 'cry.png',
	';-('  => 'cry.png',
	');'  => 'cry.png',
	')-;'  => 'cry.png',
	':B'  => 'toothy.png',
	':-B'  => 'toothy.png',
	':Z'  => 'sleep.png',
	':-Z'  => 'sleep.png',
	'(lolo)'  => 'laugh.png',
	';|'  => 'bored.png',
	':8)'  => 'sunglasses.png',
	'(e)'  => 'embarrassed.png',
	':*'  => 'kiss.png',
	'(l)'  => 'love.png',
	';O'  => 'retard.png',
	':aw:'  => 'awesomeface.png',
	':oops:'  => 'oops.png',
	':&lt;'  => 'duh.png',
	':X'  => 'nospeak.png',
	':#'  => 'zipped.png',
	':@'  => 'blag.png',
	'=|'  => 'lookdown.png',
	':nerd:'  => 'nerd.png',
	':{'  => 'disappoint.png',
	':fffuuu:'  => 'fffuuu.png',
	':facepalm:'  => 'facepalm.png',
	':?'  => 'question.png',
	':tu:'  => 'thumbsup.png',
	':td:'  => 'thumbsdown.png',
	'(XD)'  => 'xd.png',
	'(X()'  => 'xsad.png',
	'(XP)'  => 'dead.png',
	':angry:'  => 'angry.png',
	':pirate:'  => 'pirate.png',
	'(OX)'  => 'skullcrossbones.png',
	);

?>
